version: "3.8"

services:
  service1:
    build: ./service_1
    container_name: service1
    expose:
      - "8001"

  service2:
    build: ./service_2
    container_name: service2
    expose:
      - "8002"

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
